DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
 'Main',
 'Snack',
 'Lunch',
 'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(12,2) NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOLEAN DEFAULT false,
  category grocery NOT NULL
);

-- psql -U dunder_mifflin -d knex-practice-test -f ./sql-scripts/create.shopping-list.sql
