INSERT INTO blogful_articles (title, content, date_published)
VALUES
  ('The Fighting Cocks & the Eagle', 'Once there were two Cocks living in the same farmyard who could not bear the sight of each other. At last one day they flew up to fight it out, beak and claw. They fought until one of them was beaten and crawled off to a corner to hide.', '2010/01/01'),
  ('The Ass in the Lion''s Skin', 'An Ass found a Lion''s skin left in the forest by a hunter. He dressed himself in it, and amused himself by hiding in a thicket and rushing out suddenly at the animals who passed that way. All took to their heels the moment they saw him.', '2010/02/01'),
  ('The Cock & the Fox', 'A Fox was caught in a trap one fine morning, because he had got too near the Farmer''s hen house. No doubt he was hungry, but that was not an excuse for stealing. A Cock, rising early, discovered what had happened. He knew the Fox could not get at him, so he went a little closer to get a good look at his enemy.', '2010/03/01'),
  ('The Wolves & the Sheep', 'A pack of Wolves lurked near the Sheep pasture. But the Dogs kept them all at a respectful distance, and the Sheep grazed in perfect safety. But now the Wolves thought of a plan to trick the Sheep.', '2010/04/01'),
  ('The North Wind & the Sun', 'The North Wind and the Sun had a quarrel about which of them was the stronger. While they were disputing with much heat and bluster, a Traveler passed along the road wrapped in a cloak.', '2010/05/01'),
  ('The Mole & his Mother', 'A little Mole once said to his Mother: "Why, Mother, you said I was blind! But I am sure I can see!"', '2010/06/01'),
  ('The Lion''s Share', 'A long time ago, the Lion, the Fox, the Jackal, and the Wolf agreed to go hunting together, sharing with each other whatever they found.', '2010/07/01'),
  ('The Lion, the Ass, & the Fox', 'A Lion, an Ass, and a Fox were hunting in company, and caught a large quantity of game. The Ass was asked to divide the spoil. This he did very fairly, giving each an equal share.', '2010/08/01'),
  ('Jupiter & the Monkey', 'There was once a baby show among the Animals in the forest. Jupiter provided the prize. Of course all the proud mammas from far and near brought their babies. But none got there earlier than Mother Monkey. Proudly she presented her baby among the other contestants.', '2010/09/01'),
  ('The Swallow & the Crow', 'The Swallow and the Crow had an argument one day about their plumage.', '2010/10/01'),
  ('The Wolf, the Kid, & the Goat', 'Mother Goat was going to market one morning to get provisions for her household, which consisted of but one little Kid and herself.', '2010/11/01'),
  ('The Miller, His Son, & the Ass', 'One day, a long time ago, an old Miller and his Son were on their way to market with an Ass which they hoped to sell. They drove him very slowly, for they thought they would have a better chance to sell him if they kept him in good condition. As they walked along the highway some travelers laughed loudly at them.', '2010/12/01'),
  ('The Ass & His Shadow', 'A Traveler had hired an Ass to carry him to a distant part of the country. The owner of the Ass went with the Traveler, walking beside him to drive the Ass and point out the way.', '2011/01/01'),
  ('The Cat & the Old Rat', 'There was once a Cat who was so watchful, that a Mouse hardly dared show the tip of his whiskers for fear of being eaten alive. That Cat seemed to be everywhere at once with his claws all ready for a pounce. At last the Mice kept so closely to their dens, that the Cat saw he would have to use his wits well to catch one. So one day he climbed up on a shelf and hung from it, head downward, as if he were dead, holding himself up by clinging to some ropes with one paw.', '2011/02/01'),
  ('The Lark & Her Young Ones', 'A Lark made her nest in a field of young wheat. As the days passed, the wheat stalks grew tall and the young birds, too, grew in strength. Then one day, when the ripe golden grain waved in the breeze, the Farmer and his son came into the field.', '2011/03/01'),
  ('The Bees & Wasps, & the Hornet', 'A store of honey had been found in a hollow tree, and the Wasps declared positively that it belonged to them. The Bees were just as sure that the treasure was theirs. The argument grew very pointed, and it looked as if the affair could not be settled without a battle, when at last, with much good sense, they agreed to let a judge decide the matter. So they brought the case before the Hornet, justice of the peace in that part of the woods.', '2011/04/01'),
  ('The Shepherd & the Lion', 'A Shepherd, counting his Sheep one day, discovered that a number of them were missing.', '2011/05/01'),
  ('The Animals & the Plague', 'Once upon a time a severe plague raged among the animals. Many died, and those who lived were so ill, that they cared for neither food nor drink, and dragged themselves about listlessly. No longer could a fat young hen tempt Master Fox to dinner, nor a tender lamb rouse greedy Sir Wolf''s appetite.', '2011/06/01'),
  ('The Stag, the Sheep, & the Wolf', 'One day a Stag came to a Sheep and asked her to lend him a measure of wheat. The Sheep knew him for a very swift runner, who could easily take himself out of reach, were he so inclined. So she asked him if he knew someone who would answer for him.', '2011/07/01'),
  ('The Eagle & the Kite', 'An Eagle sat high in the branches of a great Oak. She seemed very sad and drooping for an Eagle. A Kite saw her.', '2011/08/01'),
  ('The Flies & the Honey', 'A jar of honey was upset and the sticky sweetness flowed out on the table. The sweet smell of the honey soon brought a large number of Flies buzzing around. They did not wait for an invitation. No, indeed; they settled right down, feet and all, to gorge themselves. The Flies were quickly smeared from head to foot with honey. Their wings stuck together. They could not pull their feet out of the sticky mass. And so they died, giving their lives for the sake of a taste of sweetness.', '2011/09/01'),
  ('The Fox & the Monkey', 'At a great meeting of the Animals, who had gathered to elect a new ruler, the Monkey was asked to dance. This he did so well, with a thousand funny capers and grimaces, that the Animals were carried entirely off their feet with enthusiasm, and then and there, elected him their king.', '2011/10/01')
;
  
